DETECTO:
  CORNER:
    CLASSES:
      - top_left
      - top_right
      - bottom_left
      - bottom_right
    CHECKPOINT: './src/weight/detect_corner.pth'
  INFO:
    CLASSES:
      - id
      - name
      - date
    CHECKPOINT: './src/weight/detect_id.pth'

CRNN:
  VOCAB: " /0123456789ABCDGHIKLMNOPQRSTUVXYÀÁÂÃÊÌÍÐÒÓÔÕÙÚÝĂĐĨŨƠƯẠẢẤẦẬẮẰẶẾỀỂỄỆỊỌỐỒỔỖỘỚỜỢỤỦỨỪỮỰỲỸ-"
  CHECKPOINT: './src/weight/crnn.pth'
  TRAINING:
    DATA_DIR: ../../../data_rec/data/
    SAVE_DIR: ./checkpoints/
    EPOCHS: 50
    LR: 0.001
    WEIGHT_DECAY: 0.001
    CLIP_NORM: 5
  BATCH_SIZE: 32
  WIDTH: 512
  HEIGHT: 50
  MAP_TO_SEQ_HIDDEN: 64
  RNN_HIDDEN: 256
  NORMLIZE:
    MEAN:
      - 0.485
      - 0.456
      - 0.406
    STD:
      - 0.229
      - 0.224
      - 0.225
  PAD:
    PADDING:
      - 3
      - 0
      - 3
      - 0
    FILL: 200
    
